"""add current date column

Revision ID: 18d67b8b6978
Revises: 58043c420463
Create Date: 2020-04-28 14:56:19.951232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d67b8b6978'
down_revision = '58043c420463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_current_date'), 'users', ['current_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_current_date'), table_name='users')
    op.drop_column('users', 'current_date')
    # ### end Alembic commands ###
