"""add 5 puzzle

Revision ID: 49bed15774cb
Revises: 18d67b8b6978
Create Date: 2020-04-28 15:33:03.772807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49bed15774cb'
down_revision = '18d67b8b6978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('puzzle_1', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('puzzle_2', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('puzzle_3', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('puzzle_4', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('puzzle_5', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'puzzle_5')
    op.drop_column('users', 'puzzle_4')
    op.drop_column('users', 'puzzle_3')
    op.drop_column('users', 'puzzle_2')
    op.drop_column('users', 'puzzle_1')
    # ### end Alembic commands ###
