"""add register time

Revision ID: 4ab4cddd2a6e
Revises: 49bed15774cb
Create Date: 2020-04-30 13:04:55.836422

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4ab4cddd2a6e'
down_revision = '49bed15774cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('register_time',
                  sa.DateTime(),
                  server_default=sa.text("CURRENT_TIMESTAMP"),
                  nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'register')
    # ### end Alembic commands ###
