"""create table user

Revision ID: 58043c420463
Revises: 
Create Date: 2020-04-27 21:01:20.750973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58043c420463'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('current', sa.Integer(), server_default='0', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_current'), 'users', ['current'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_current'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
