"""add puzzle 6

Revision ID: de08e605e0cb
Revises: 4ab4cddd2a6e
Create Date: 2020-04-30 17:50:55.983972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de08e605e0cb'
down_revision = '4ab4cddd2a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('puzzle_6', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'puzzle_6')
    # ### end Alembic commands ###
